version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 velocity_media.wsgi:application
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

